# .air.toml at project root
root = "."
tmp_dir = "tmp"

[build]
# Build the binary specified by $TARGET
cmd = "go build -o ./tmp/main ./cmd/$TARGET"
bin = "tmp/main"
full_bin = "tmp/main"
include_ext = ["go", "html", "css", "js"]
exclude_dir = ["tmp", "vendor", ".git"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
